<a href="https://colab.research.google.com/github/kittimaxz/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Function**

``` python
     def  function_name(_Input_) :

       do_something with _Input_  to produce  _Output_

       return  _Output_
```

```blacklick กด ~ ค้าง,alt -9>6 (full keybord with number) #อีกวิธีคือกดปุ่ม window,Alt พร้อมกันแล้วกดเลข 9,6 

function มีส่วนประกอบสำคัญทั้งหมด 4 ส่วน


1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)
2. กำหนดตัวแปรที่จะเป็น input Input (ขาดได้)
3. ส่วนประมวลผล do_something with Input to get (ขาดไม่ได้)
4. ส่วน output return Output (ขาดได้)

เราใช้เว้นวรรค(indent) เพื่อบอกขอบเขตของ code

#### สร้างฟังก์ชั่น

In [1]:
def print_name(name,surname,ID) :
    st=f'=ชื่อ {name} นามสกุล {surname} ID {ID}' # code ในฟังก์ชั่นต้องเว้นวรรค
    return st
print('outside function')

outside function


การเรียกใช้ฟังก์ชั่น

In [2]:
print_name('กิตติมา','อุปสุข','623021040-9')

'=ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9'

In [3]:
output_string = print_name('กิตติมา','อุปสุข','623021040-9')
print(output_string)

=ชื่อ กิตติมา นามสกุล อุปสุข ID 623021040-9


ฟังก์ชั่นไม่จำเป็นต้องมี output

In [ ]:
def print_name2(surname,ID,name) :
    st=f' ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)

In [4]:
print_name2('กิตติมา','อุปสุข','623021040-9')

NameError: ignored

In [ ]:
op2=print_name2('กิตติมา','อุปสุข','623021040-9')

In [ ]:
print(op2)

ฟังก์ชั่นไม่จำเป็นต้องมี input

In [ ]:
def Pi() :
  return 3.14159265359

In [ ]:
#คำนวณพื้นที่วงกลมมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

In [ ]:
def print_my_name() :
    print('กิตติมา อุปสุข 623021040-9')

In [ ]:
print_my_name()

input ของ function ใน python มีสองแบบ input ที่จำเป็นต้องใส่ (มีค่า default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน 

เราต้องเรียง input  ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name,surname,ID,grade='F') :
    st=f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [ ]:
print_2lines_default('กิตติมา','อุปสุข','623021040-9')

In [ ]:
print_2lines_default('กิตติมา','อุปสุข','623021040-9','A')

เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

In [ ]:
print_name2(name='กิตติมา', surname='อุปสุข', ID='623021040-9')

HW3 ให้เขียน function คำนวณจำนวนวินาทีจากเวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [5]:
def time(t):
 time_sp=t.split('-')
 h1=int (time_sp[0])*3600
 m1=int (time_sp[1])*60
 s1 =int (time_sp[2])
 ans = h1+m1+s1
 print(f'เวลา {t} สามารถแปลงเป็นวินาทีได้เป็น {ans} วินาที')

In [6]:
time('14-15-31')

เวลา 14-15-31 สามารถแปลงเป็นวินาทีได้เป็น 51331 วินาที


In [7]:
time('13-00-01')

เวลา 13-00-01 สามารถแปลงเป็นวินาทีได้เป็น 46801 วินาที


In [8]:
time('05-49-44')

เวลา 05-49-44 สามารถแปลงเป็นวินาทีได้เป็น 20984 วินาที


In [9]:
time('00-00-16')

เวลา 00-00-16 สามารถแปลงเป็นวินาทีได้เป็น 16 วินาที


*ไม่เอา* *pandas *

Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num+py -> Number-Numerical+python

การใช้ package
1. ```import``` ```ชื่อ  package ``` #เรียกใช้ package
2. ```ชื่อ package.ชื่อฟังก์ชัน``` #เรียกใช้ function



In [14]:
import numpy

data structure -> array #data structure คือโครงสร้างของข้อมูล

สร้าง array (numpy array)

In [16]:
mat_ex1=numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [17]:
mat_ex1[1,1] #[แถว,หลัก] ใน python จะเริ่มที่ 0,1,2,.....

0.1

ถ้าไม่มี numpy array

In [18]:
list_ex1=[[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [21]:
list_ex1[1][1] #เป็นการเรียก list ใหม่ขึ้นมาอีกหนึ่งตัว 

0.1

In [23]:
print(list_ex1)
a=list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix (2D array),scalar (ตัวเลขค่าคงที่)

In [24]:
mat_ex1=numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2=numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกกัน

(หน้าตาของ matrix ต้องเหมือนกัน)

In [26]:
mat_ex0=numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [25]:
mat_ex3=mat_ex1+mat_ex2 
print(mat_ex3)
mat_ex4=mat_ex1-mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [27]:
mat_ex1+mat_ex0

ValueError: ignored

การตรวจสอบขนาดของ matrix  

In [28]:
mat_ex3.shape

(2, 3)

In [29]:
mat_ex3.shape[0]

2

คูณ matrix

In [39]:
print(mat_ex1)
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [30]:
mat_ex1*mat_ex2 #อันนี้ไม่ถูก เป็นการคูณกันแบบเหมือนที่เราบวก,ลบธรรมดา

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

การคูณ matrix (แถวคูณหลัก)

(หลักของ matrix ตัวข้างหน้า ต้องเท่ากับแถวของ matrix ตัวข้างหลัง)

dot product ((AAA,x),(x,ZZZ))=(AAA,ZZZ)

In [36]:
numpy.dot(mat_ex1,mat_ex2) #เพราะแถวกับหลักของทั้ง 2 matrix ไม่เท่ากัน

ValueError: ignored

In [37]:
mat_ex3=mat_ex1+mat_ex2 
print(mat_ex3)
mat_ex4=mat_ex1-mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

```
matrix.T
```



In [40]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [41]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [42]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [35]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3)(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [44]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3)=(3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)